x = int(input("numero"))
if(x<10):
    y = x * 1
    print ("Resultado=", y)
    y = x * 2
    print ("Resultado=", y)
    y = x * 3
    print ("Resultado=", y)
    y = x * 4
    print ("Resultado=", y)
    y = x * 5
    print ("Resultado=", y)
    y = x * 6
    print ("Resultado=", y)
    y = x * 7
    print ("Resultado=", y)
    y = x * 8
    print ("Resultado=", y)
    y = x * 9
    print ("Resultado=", y)
    y = x * 10
    print ("Resultado=", y)
